server:
  port: 8181

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-book 
          uri: lb://MS-BOOK
          predicates:
            - Path=/ms-book/** 
          filters:
            - RewritePath=/ms-book/(?<remaining>.*), /$\{remaining}  

        - id: ms-client
          uri: lb://MS-CLIENT
          predicates:
            - Path=/ms-client/** 
          filters:
            - RewritePath=/ms-client/(?<remaining>.*), /$\{remaining}  

        - id: ms-loan 
          uri: lb://MS-LOAN
          predicates:
            - Path=/ms-loan/** 
          filters:
            - RewritePath=/ms-loan/(?<remaining>.*), /$\{remaining}          
