server:
  port: 8181

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-book 
          uri: lb://MS-BOOK
          predicates:
            - Path=/ms-book/** 
          filters:
            - RewritePath=/ms-book/(?<remaining>.*), /$\{remaining}  
