### Obtener lista de préstamos de libros
GET http://localhost:8990/v1/api/loans
Accept: application/json


### Obtener lista de préstamos de libros
GET http://localhost:8990/v1/api/loanDetails
Accept: application/json
